# Generated by Django 4.2.27 on 2026-02-06 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_product_farmer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='land_size',
            field=models.FloatField(blank=True, help_text='Size in acres', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_coordinates',
            field=models.CharField(blank=True, help_text='Latitude, Longitude', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('SILT', 'Silt'), ('CLAY', 'Clay'), ('LOAM', 'Loam'), ('SANDY', 'Sandy'), ('PEAT', 'Peat'), ('CHALK', 'Chalk')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CropPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_variety', models.CharField(max_length=100)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('estimated_volume', models.FloatField(default=0.0, help_text='Estimated harvest in kg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
