# Generated by Django 4.2.27 on 2026-02-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_land_size_profile_location_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location_coordinates',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='Location details or coordinates', max_length=100, null=True),
        ),
    ]
