# Generated by Django 4.2.27 on 2026-02-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_location_coordinates_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SEEDS', 'Seeds'), ('FERTILIZER', 'Fertilizer'), ('LABOR', 'Labor'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('crop_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.cropplan')),
            ],
        ),
    ]
