# Generated by Django 4.2.27 on 2026-02-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
